---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  vars:
    wifi:
      name: "WeeFee"
      pass: "noneyabiz"

  tasks:
    - name: Configure wifi by templating the wpa config
      template: src=templates/wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf

    - name: Setup plex!
      become: True
      include_role:
        name: plex_setup
