---
  - name: add plex public key
    apt_key:
      url: https://dev2day.de/pms/dev2day-pms.gpg.key

  - name: add plex repo
    shell: echo "deb https://dev2day.de/pms/ stretch main" >> /etc/apt/sources.list.d/pms.list

  - name: install important transport package
    apt:
      name: apt-transport-https
      update_cache: yes

  - name: install plex
    apt:
      name: plexmediaserver-installer
      update_cache: yes

  - lineinfile:
      dest: /etc/default/plexmediaserver.prev
      regexp: '^\PLEX_MEDIA_SERVER_USER='
      line: 'PLEX_MEDIA_SERVER_USER=pi'
      state: present
